### ISSUE TITLE
PlayerFragment crashes when opened with the system-wide dark mode

### ISSUE THREAD

**Issue by squivix** [Benji377/SocyMusic#155]
**Describe the Bug**
I had this bug that confused the heck out of me. The player fragment kept crashing with an exception that I didn't understand at all. After some googling and dubugging I found that it was due to the playerBackground style attribute used to set different backgrounds in the player fragment. I remembered not having this error a few days ago so I was so confused at first. Then it hit me: I had turned on the dark mode. If you have the system-wide dark mode turned on in the settings (the one introduced in android 9), the app uses the (night) version of themes.xml which in our case does not set the playerBackground attribute. 

Updating the night themes.xml should fix the crash. Ideally we should have light versions of the themes in our normal themes file and dark versions in the night themes file.

**To Reproduce**
1. Turn on system-wide dark mode in settings.
2. Open any song.

**Comment by Benji377** [comment]
I actually thought about this while adding the themes. I think I wanted to transfer all the files over to the darktheme file and force permanent darkmode on the app. The reason for only allowing darkmode is that it looked much better since some stuff like the settings and popuo don't seem to look that good with lightmode.

But then I forgot about it. I think it should easily be fixed by copy pasting the themes from one files to the other, but I will need to look into that

**Comment by Benji377** [comment]
According to [this question](https://stackoverflow.com/questions/60026842/how-do-i-force-apply-a-dark-theme-on-android-studio) it is not possible/recommend to force apply the dark theme. This said, I will now try to solve the bug by copy pasting the themes and later se what I can do to improve the look of the pop-up and settings.
We should either turn everything white on daymode and turn everything black on nightmode or just leave everything black.
