### ISSUE TITLE
App crashes when clicking the 'back' button

### ISSUE THREAD

**Issue by Benji377** [Benji377/SocyMusic#20]
The idea of having a bar at the bottom is great! I can see it when I click the 'back' button on the phone, but immediately afterward, the app crahes. When I open it back up there is no bar, just the home screen.

**Comment by Benji377** [comment]
@squivix Is it working on your phone?

**Comment by squivix** [comment]
It's not working on my phone. This is something I noticed actually but forgot to fix. The app doesn't crash, it just closes because the only activity has been backed away from. 

 Should be fixed by pull request #21. Now the back button will close the bottom bar first if the bottom bar is open, otherwise it will close the app.
