### ISSUE TITLE
Song title updates every second along with the playtime, making the marquee text scroll look buggy

### ISSUE THREAD

**Issue by squivix** [Benji377/SocyMusic#22]
For some weird reason, in the PlayerFragment, the song title text box keeps updating on its own even though the title didn't change. This makes the infinite marquee scroll reset every second. I noticed that the updates are synced with the runtime TextView which makes me think it's related somehow.

[This thread](https://stackoverflow.com/questions/11856875/textview-restarts-marquee-when-changing-another-textview-in-same-linearlayout) on StackOverflow seems to be talking about the same problem but I tried the solutions there and they didn't work. Here's  screen grab:

<img src="https://user-images.githubusercontent.com/55770995/120746449-e86f8e00-c507-11eb-8ffe-d180c3bd49d3.gif" width="250" height="444"/>

**Comment by Benji377** [comment]
Ok, so the issue is about the songName_textview which gets declared on line 32 in the PlayerFragment.java.
Afterward, it gets initialized on line 65 and gets the title of the song assigned at line 75.

The title gets assigned again in the updateSongPlaying() method. Which gets called every time the next or previous button is pressed.

**Comment by Benji377** [comment]
Ok, I think I fixed it. The solution on Stackoverflow was actually correct, I added an onLayoutChange to the textview and now it works (Line 77 - 87 in PlayerFragment). 
Gonna create a pull request now.
